### ISSUE TITLE
Create private key and address from big integer

### ISSUE THREAD

**Issue by mehranj73** [raugfer/crypto-java#5]
Is it possible to create private keys from my own big integer. Also how many address types your library supports? Can I create p2sh or Segwit addresses? Thanks

**Comment by mehranj73** [comment]
please

**Comment by vae520283995** [comment]
> Is it possible to create private keys from my own big integer.

Yes
```
String privateKey = wallet.privatekey_encode(your big integer, true, "bitcoin", false);
```
> Also how many address types your library supports? Can I create p2sh or Segwit addresses? Thanks

No, creating p2sh and segwit means creating new encoding and decoding formats, of course you can integrate them, I also implemented it, but the project has been modified a lot, so I can’t pull request

**Comment by mehranj73** [comment]
How can I get the address now? I really like what has been done here, I wish I'll learn to write my own code but the naming conventions have not been followed and functions and parameter names are not clear about their functionality.

**Comment by mehranj73** [comment]
`val a = wallet.address_encode(BigInteger("2"), "address", "ethereum", false)`

I found this. Is this correct?

**Comment by vae520283995** [comment]
```
String privateKey = wallet.privatekey_encode(your big integer, true, "bitcoin", false);
String publicKey = wallet.publickey_from_privatekey(privateKey, "bitcoin", false);
String address = wallet.address_from_publickey(publicKey , "bitcoin", false);
```
