### ISSUE TITLE
how to extend more coin?

### ISSUE THREAD

**Issue by pangoo-reuse** [raugfer/crypto-java#6]
how to extend more coin?
please give me any suggest,thx.

**Comment by raugfer** [comment]
At this library level, you can see examples of how to do it in the following commits:

- Adds support for native FTM on Fantom
https://github.com/raugfer/crypto-java/commit/ad46272eeb0aeaa7a9792492c3f694c125d507d7

- Adds support for ERC-20 tokens on Ethereum
https://github.com/raugfer/crypto-java/commit/7b39092ef9d517ab5bd42013c6509e3992b9ed63
